services:
  - type: web
    name: pro-job-aggregator
    env: python
    buildCommand: ""
    startCommand: gunicorn run:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
